### ISSUE TITLE
language switching on browse page wrong url

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#106]
I'm working locally on the family letters app and noticed that when switching from the non-default language back to the default language when on a specific facet's browse page, the language switching link goes to the wrong page.

From `http://localhost:3000/en/browse/format`
Click `es`
Instead of `http://localhost:3000/browse/format`
It takes me to `http://browse/format`

I did some more testing and this is the only page I've seen this on.  The `en` (non-default) language link works when switching from the default to the non-default, but even while `es` is the selected language, the `es` link will still have the incorrect path.

**Comment by techgique** [comment]
Oh no! Interesting that it's happening just in one place from your account. Strange that it outputs a link like that. That makes me think it must be writing the whole link as `<a href="http://browse/format">` rather than how it commonly does root-relative links like `<a href="/browse/format">` :thinking:
