### ISSUE TITLE
check if subtitle before adding tags

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#113]
Some sites will not have a subtitle, so we should plan for that instead of using empty tags

https://github.com/CDRH/orchid/blob/dev/app/views/layouts/body/_header.html.erb#L8

**Comment by jduss4** [comment]
@karindalziel is gonna do this but change a bunch of stuff (and then update family letters and cather to override the new default behavior)

**Comment by karindalziel** [comment]
I think the title html should look something like this: 

`<h1><span="maintitle">MAIN TITLE</span> <span class="subtitle">The sub title</span></h1>`

Alternatively, this is how bootstrap handles (sort of) extra heads. I don't love it because I'm not sure of the semantic meaning of `<small>` in this context. But if we want to follow bootstrap, this is a possibility: 

`<h1>h1. Bootstrap heading <small>Secondary text</small></h1>`

Note: bootstrap 4 does it this way: 

```
<h3>
  Fancy display heading
  <small class="text-muted">With faded secondary text</small>
</h3>
```

**Comment by techgique** [comment]
The latter seems a little more semantic with the element name, so I'm open to that. Though you'll probably still want a class on the main title so you can style it separately too, right?

**Comment by karindalziel** [comment]
@techgique yes, would definitely like a span around the main title for styling either way 👍

**Comment by jduss4** [comment]
Interestingly, because orchid itself has defaults filled into the en.yml file, there is ALWAYS a title, so the only way to check for it as is would be perhaps to check for an empty string...?  Or I just comment out those configs from the yaml file and figure that there will always have to be something in the user file for it.

**Comment by jduss4** [comment]
I think this got taken care of in the last few weeks, right?

**Comment by techgique** [comment]
I believe this was taken care of too
