### ISSUE TITLE
orchid default scss is not being included

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#117]
I was making alterations to the default orchid theme's stylesheet and growing frustrated that my selects weren't working, when I finally discovered that perhaps the sheet wasn't being included at all?

Although there is a line in the `application.scss`:
```
// Import Orchid-wide styling from Orchid gem
@import "orchid";
```

There are also lines in `stylesheets/orchid.scss` that say:
```
// Orchid's stylesheets declared for auto and pre-compilation in
// javascripts/orchid.js because link_tree directive does not work here
```

When you go there:
https://github.com/CDRH/orchid/blob/dev/app/assets/javascripts/orchid.js#L5
```
//= link_tree ../stylesheets/orchid
```
I'm not sure that the above includes `stylesheets/orchid.scss`.  I moved the file into `stylesheets/orchid` and then got an error that it couldn't find the bootstrap variables required by the stylesheet.

Is the default orchid stylesheet being included somehow outside of the places I mention above?  If not, we gotta figure out how to get it to see the bootstrap variables.  If so....then how can I get my changes to it do render?  I am guessing it is not being included correctly because I could insert syntax errors and not see a resulting rails error in the app.

**Comment by techgique** [comment]
This has to be something specific to the app you're working on or your computer. :persevere:  Family Letters on dev1 relies on `orchid.scss` for styling the language links in the header. Particularly the `.language_link` class. You can see the lines in the [CSS file linked to by the pages](https://cdrhdev1.unl.edu/family_letters/assets/application.self-aa82b8f2f6ee2e7fc309afb8363869e836788d406ce8489c3038fae2f2546ce3.css). Search for "orchid" and you'll see where it's importing them from and how they output. So comparing your files to dev1's may be a good starting point.

The `@import "orchid";` line in `application.scss` (that's copied into the parent app by the Orchid generator) is what should be importing the styles from the Orchid engine's file at `app/assets/stylesheets/orchid.scss`.

This is kind of unrelated to your `orchid.scss` not importing and updating with your changes, but I know why you're getting the error related to the bootstrap variables when you moved the file into `stylesheets/orchid/`. It's because that's when the `link_tree ../stylesheets/orchid` directive compiles all the files in that directory independently to avoid asset precompile errors. Putting the @import for the bootstrap variables at the beginning of every SCSS file that references them is the fix there. And it looks like we'll need to move a couple font imports out of the current `bootstrap-variables.scss` in Orchid so that doesn't result in duplicated output. We only want `$abc_xyz` variable assignments in that file.

**Comment by jduss4** [comment]
Re: the last point, Karin and I did add the @import for the bootstrap-variables in there, and it wasn't having it, unfortunately, but the error was enough to satisfy me that at least it was loading!

This was on the cody_archive site I do believe.  If you have a minute on Monday I can try to recreate the problem!

**Comment by jduss4** [comment]
I agree that we should move the font, let's work it into this issue:  https://github.com/CDRH/orchid/issues/116

**Comment by techgique** [comment]
I believe this was sorted out in a couple separate issues for a fonts partial and getting everyone on the same page about needing to import bootstrap variables at the top of each Sass file.
