### ISSUE TITLE
Remaining Route Abstraction

### ISSUE THREAD

**Issue by techgique** [CDRH/orchid#127]
- I think we can most simply scope sections to the items in the API we want by setting section-wide `api_options` akin to how we had the entire Letters app scoped to subcategory letters
    - I wonder if we can move the code that handles this into a method that can be overridden in the main app with logic determining what API options to send when a request is sent to particular sections
    - Perhaps there is a way to define it in a YAML file instead, which may be more accessible even though working with this aspect of Orchid will likely be handled by developers
- Facets and their corresponding translations will need to be definable for independent sections
- We want links for search results to point to URLs in specific sections
    - I mentioned possibly adding a field to the API schema, but Karin suggested we aim to match an API item's category and subcategory to the URL scoping in our routes
        - This approach could potentially be a road block if we have more than two levels to our URL scoping. If we can make it work this way for now and avoid adding another API field, I think we should go forward with that approach while we are able and deal with complications in the future
- Orchid will need the ability to draw a route more than once. Currently it will only draw a route once and add the route's name to an array of names that it won't draw again
    - I'm thinking we could handle the already drawn arrays by putting them in a hash whose key is the section name, where the root routes' section name would be `root`
    - I think we might change what routes are drawn from a negative list to a positive list of the route names we do want drawn. Wondering if this will be shorter and easier to read
        - Error routes will only ever need to be drawn in root scope (unless we want custom error pages in sections), so we might be able to handle them differently in the code to shorten the negative / positive list length

Keep in mind that we want to keep things as simple as possible for use in the main app, even if it requires slightly more tricky underlying code in Orchid. Documentation will be vital

**Comment by jduss4** [comment]
> I wonder if we can move the code that handles this into a method that can be overridden in the main app with logic determining what API options to send when a request is sent to particular sections

I agree, it seems like at bare minimum we should pull out most of the abstractable logic from the "search" (index) action so that we can call it from other places with new options, without being tied to the actual action and therefore the view it's rendering itself

> Facets and their corresponding translations will need to be definable for independent sections

I was kind of thinking about this last night.  Seems like maybe we can harness the yaml power of the `<<: *variable` notation so that if we need to duplicate chunks between sections we can more easily.  We also need to ask ourselves if we need backwards compatibility.  If so, then I guess we could do something like "look for a key with the section name, if none found, use `en` or `es` as needed.  Maybe something like the following would keep backwards compatibility for those sites which aren't using scopes?

```
en:
  ... non scoped app or / portion of app
es:
  ...
section:
  en:
    ...  scoped section uses these?
  es:
    ...
```

> links for search results to point to URLs in specific sections

I agree that I would prefer these are not in the API, but for a different reason than Karin -- that would be yet another field that any external users querying the API would not need to use, and it would be rails specific and therefore not particularly useful for anything else besides Orchid (at this point in time).  I agree with you that for now we can probably push ahead without needing it!

> Orchid will need the ability to draw a route more than once

Can you explain this a little bit more?  I think I don't quite understand how the scoping is being defined in Orchid, possibly, I thought that a route (say, 'home_path') would show up both at `/` and at `section/` once everything is scoped....is that not already implemented?

Don't feel like you need to respond while you're on vacation!!!

**Comment by jduss4** [comment]
@techgique has this been resolved in the sections PR ?

**Comment by techgique** [comment]
Yes, I believe everything mentioned here has been implemented :)
