### ISSUE TITLE
explore making search results sort configurable

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#40]
The Cather Letters are probably going to need to be able to sort on ID.  Is this something that we should override the whole partial / helper for?  Could we instead use a configuration / smaller override somehow?

**Comment by techgique** [comment]
I had thought about tying in the config file when working on my sorting PR but thought handling the default sort would be more time-consuming so I decided it could wait.
My initial thought upon seeing this issue was this would be a good candidate for figuring out overriding helper methods. But if you have an idea on how to do it with the config file, I'm willing to take a look :)

**Comment by jduss4** [comment]
Closed by https://github.com/CDRH/orchid/pull/43
